name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Show branch name
        run: echo "Nom branche > ${{ github.ref }}"
      - name: Show OS VM
        run: echo "OS VM > ${{ runner.os }}"
      - name: Show python version
        run: python --version